### PR TITLE
Update content.tex

### PR DESCRIPTION
**Pull request by samialabed**
Deprecate old sections, fix typo in graph adj data structure

### CODE REVIEW

**Comment by Todd-Davies** [comment]
Feel free to add yourself to the course_info.tex as a contributor, like so: 
https://github.com/Todd-Davies/first-year-notes/blob/cc41db51b847544dc2b14447c6c5ee4927b9288b/COMP11120_2/course_info.tex#L54

If not, I'll do it when I re-compile the pdf's.

**Comment by samialabed** [comment]
I can add a contributors section in a separate CL if you want, since I am adding some of the new content in that one.

**Comment by Todd-Davies** [comment]
I don't mind :) I think it's fine to have multiple commits doing different stuff in the same PR, so long as each commit does one atomicish thing.

**Comment by samialabed** [comment]
Going to close this PR then, changes I wanted to make ended up being too complicated to do through the github UI and ended having to fork the thing and start new PR  >.>

**Pull request closed without merging**
